"""added sync parameters

Revision ID: 003557e07eb9
Revises: 20260617_0008
Create Date: 2026-06-17 12:18:26.871680

"""
from alembic import op
import sqlalchemy as sa



revision = '003557e07eb9'
down_revision = '20260617_0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_provider_conversation_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_reference_id'), table_name='conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_reference_id'), 'conversations', ['reference_id'], unique=False)
    op.create_index(op.f('ix_conversations_provider_conversation_status'), 'conversations', ['provider_conversation_status'], unique=False)
    # ### end Alembic commands ###
