"""Removed feedback status from daily entry

Revision ID: 17431a2f681a
Revises: 817a03ed9218
Create Date: 2026-08-05 11:15:31.227212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '17431a2f681a'
down_revision = '817a03ed9218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pms_daily_task_entries', 'feedback_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pms_daily_task_entries', sa.Column('feedback_status', postgresql.ENUM('GIVEN', 'PENDING', name='pms_feedback_status'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
