"""add_offers_table

Revision ID: 1c7ceb778a1d
Revises: 56fe57995092
Create Date: 2026-07-04 15:51:15.287592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '1c7ceb778a1d'
down_revision = '56fe57995092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('offer_data', sa.JSON(), nullable=True))
    op.alter_column('offers', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('offers', 'listing_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('offers', 'offer_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('offers', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('offers', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offer_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('offers', 'direction',
               existing_type=postgresql.ENUM('INCOMING', 'OUTGOING', name='offer_direction'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'OUTGOING'::offer_direction"))
    op.alter_column('offers', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('offers', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_offers_account_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_conversation_id'), table_name='offers')
    op.drop_constraint(op.f('uq_offers_provider_offer_id'), 'offers', type_='unique')
    op.create_index(op.f('ix_offers_buyer_username'), 'offers', ['buyer_username'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    op.create_index(op.f('ix_offers_provider_offer_id'), 'offers', ['provider_offer_id'], unique=True)
    op.drop_constraint(op.f('offers_conversation_id_fkey'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('offers_conversation_id_fkey'), 'offers', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_offers_provider_offer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_username'), table_name='offers')
    op.create_unique_constraint(op.f('uq_offers_provider_offer_id'), 'offers', ['provider_offer_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_offers_conversation_id'), 'offers', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_offers_account_id'), 'offers', ['account_id'], unique=False)
    op.alter_column('offers', 'raw_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('offers', 'message',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('offers', 'direction',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('INCOMING', 'OUTGOING', name='offer_direction'),
               existing_nullable=False,
               existing_server_default=sa.text("'OUTGOING'::offer_direction"))
    op.alter_column('offers', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offer_status'),
               existing_nullable=False)
    op.alter_column('offers', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('offers', 'offer_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('offers', 'listing_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('offers', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('messages', 'offer_data')
    # ### end Alembic commands ###
