"""removed review note column

Revision ID: 39f78ec06804
Revises: 20260821_0047
Create Date: 2026-08-21 10:04:43.802229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '39f78ec06804'
down_revision = '20260821_0047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_record_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('cancel_id', sa.String(length=255), nullable=False),
    sa.Column('cancel_state', sa.String(length=80), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('requester', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ebay_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_record_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'cancel_id', name='uq_cancellations_account_cancel_id')
    )
    op.create_table('returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_record_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('return_id', sa.String(length=255), nullable=False),
    sa.Column('return_status', sa.String(length=80), nullable=True),
    sa.Column('return_reason', sa.String(length=255), nullable=True),
    sa.Column('return_state', sa.String(length=80), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ebay_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_record_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'return_id', name='uq_returns_account_return_id')
    )
    op.drop_column('leave_requests', 'review_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('review_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('returns')
    op.drop_table('cancellations')
    # ### end Alembic commands ###
