"""Removed break time

Revision ID: 3d1ee3134faa
Revises: 20260820_0046
Create Date: 2026-08-20 12:29:22.587200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '3d1ee3134faa'
down_revision = '20260820_0046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_policies', 'break_start_time')
    op.drop_column('leave_policies', 'break_end_time')
    op.drop_column('leave_requests', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('leave_policies', sa.Column('break_end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('leave_policies', sa.Column('break_start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
