"""make_listing_id_nullable

Revision ID: 56fe57995092
Revises: 96327c3b9b6c
Create Date: 2026-07-04 14:43:34.991437

"""
from alembic import op
import sqlalchemy as sa



revision = '56fe57995092'
down_revision = '96327c3b9b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    # ### end Alembic commands ###
