"""removed order_id and sku from product context as it was already in order context

Revision ID: 722f832c7f81
Revises: 20260629_0019
Create Date: 2026-06-29 13:20:18.857886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '722f832c7f81'
down_revision = '20260629_0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cancellations_account_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_cancel_id'), table_name='cancellations')
    op.drop_index(op.f('ix_cancellations_order_id'), table_name='cancellations')
    op.drop_index(op.f('ix_conversation_order_contexts_conversation_id'), table_name='conversation_order_contexts')
    op.drop_index(op.f('ix_conversation_order_contexts_ebay_item_id'), table_name='conversation_order_contexts')
    op.drop_index(op.f('ix_conversation_order_contexts_ebay_order_id'), table_name='conversation_order_contexts')
    op.drop_index(op.f('ix_conversation_order_contexts_listing_id'), table_name='conversation_order_contexts')
    op.drop_index(op.f('ix_conversation_order_contexts_sku'), table_name='conversation_order_contexts')
    op.drop_index(op.f('ix_conversation_product_contexts_conversation_id'), table_name='conversation_product_contexts')
    op.drop_index(op.f('ix_conversation_product_contexts_enrichment_status'), table_name='conversation_product_contexts')
    op.drop_index(op.f('ix_conversation_product_contexts_reference_id'), table_name='conversation_product_contexts')
    op.drop_index(op.f('ix_conversations_linked_order_record_id'), table_name='conversations')
    op.drop_index(op.f('ix_ebay_api_usage_usage_date'), table_name='ebay_api_usage')
    op.drop_index(op.f('ix_message_attachments_account_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_order_line_items_account_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_item_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_listing_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_order_id'), table_name='order_line_items')
    op.drop_index(op.f('ix_order_line_items_sku'), table_name='order_line_items')
    op.drop_index(op.f('ix_orders_account_external_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_username'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('reply_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('reply_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_returns_account_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_id'), table_name='returns')
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_returns_return_id'), 'returns', ['return_id'], unique=False)
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_account_id'), 'returns', ['account_id'], unique=False)
    op.alter_column('reply_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('reply_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_buyer_username'), 'orders', ['buyer_username'], unique=False)
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_account_external_created_at'), 'orders', ['account_id', 'external_created_at'], unique=False)
    op.create_index(op.f('ix_order_line_items_sku'), 'order_line_items', ['sku'], unique=False)
    op.create_index(op.f('ix_order_line_items_order_id'), 'order_line_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_listing_id'), 'order_line_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_item_id'), 'order_line_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_line_items_account_id'), 'order_line_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_account_id'), 'message_attachments', ['account_id'], unique=False)
    op.create_index(op.f('ix_ebay_api_usage_usage_date'), 'ebay_api_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_conversations_linked_order_record_id'), 'conversations', ['linked_order_record_id'], unique=False)
    op.create_index(op.f('ix_conversation_product_contexts_reference_id'), 'conversation_product_contexts', ['reference_id'], unique=False)
    op.create_index(op.f('ix_conversation_product_contexts_enrichment_status'), 'conversation_product_contexts', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_conversation_product_contexts_conversation_id'), 'conversation_product_contexts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_order_contexts_sku'), 'conversation_order_contexts', ['sku'], unique=False)
    op.create_index(op.f('ix_conversation_order_contexts_listing_id'), 'conversation_order_contexts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_conversation_order_contexts_ebay_order_id'), 'conversation_order_contexts', ['ebay_order_id'], unique=False)
    op.create_index(op.f('ix_conversation_order_contexts_ebay_item_id'), 'conversation_order_contexts', ['ebay_item_id'], unique=False)
    op.create_index(op.f('ix_conversation_order_contexts_conversation_id'), 'conversation_order_contexts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_cancellations_order_id'), 'cancellations', ['order_id'], unique=False)
    op.create_index(op.f('ix_cancellations_cancel_id'), 'cancellations', ['cancel_id'], unique=False)
    op.create_index(op.f('ix_cancellations_account_id'), 'cancellations', ['account_id'], unique=False)
    # ### end Alembic commands ###
