"""add_offer_data_and_fix_provider_case

Revision ID: 8602578c13dd
Revises: 1c7ceb778a1d
Create Date: 2026-07-04 16:15:26.241523

"""
from alembic import op
import sqlalchemy as sa



revision = '8602578c13dd'
down_revision = '1c7ceb778a1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
