"""add pms module tables

Revision ID: 87d5266f6b0c
Revises: 0846098ed9ed
Create Date: 2026-08-18 18:18:49.083504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '87d5266f6b0c'
down_revision = '0846098ed9ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pms_employee_of_month_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_tie', sa.Boolean(), nullable=False),
    sa.Column('tied_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_user_id', sa.UUID(), nullable=True),
    sa.Column('selected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selected_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_pms_eom_year_month')
    )
    op.create_table('pms_metric_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'PRODUCTIVITY_AUTO', 'QUALITY_AUTO', 'CUSTOM', name='pms_metric_source'), nullable=False),
    sa.Column('is_auto_calculated', sa.Boolean(), nullable=False),
    sa.Column('is_manually_editable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_pms_metric_configs_key')
    )
    op.create_index('ix_pms_metric_configs_display_order', 'pms_metric_configs', ['display_order'], unique=False)
    op.create_table('pms_monthly_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', name='pms_monthly_status'), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('maximum_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_pms_monthly_records_user_year_month')
    )
    op.create_index('ix_pms_monthly_records_user_id', 'pms_monthly_records', ['user_id'], unique=False)
    op.create_index('ix_pms_monthly_records_year_month', 'pms_monthly_records', ['year', 'month'], unique=False)
    op.create_table('pms_monthly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pms_monthly_record_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=60), nullable=False),
    sa.Column('metric_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('weight_snapshot', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source_snapshot', sa.String(length=30), nullable=False),
    sa.Column('is_auto_calculated_snapshot', sa.Boolean(), nullable=False),
    sa.Column('auto_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('was_overridden', sa.Boolean(), nullable=False),
    sa.Column('calc_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pms_monthly_record_id'], ['pms_monthly_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pms_monthly_metrics_record_id', 'pms_monthly_metrics', ['pms_monthly_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ebay_api_usage_api_name'), 'ebay_api_usage', ['api_name'], unique=False)
    op.alter_column('daily_task_entries', 'error_level',
               existing_type=sa.Enum('NO_ERROR', 'MINOR', 'MAJOR', name='daily_task_entry_error_level'),
               type_=postgresql.ENUM('NO_ERROR', 'MINOR', 'MAJOR', name='pms_error_level'),
               existing_nullable=False,
               existing_server_default=sa.text("'NO_ERROR'::pms_error_level"))
    op.alter_column('daily_task_entries', 'day_type',
               existing_type=sa.Enum('WORKING_DAY', 'HOLIDAY', 'SUNDAY', 'LEAVE', name='daily_task_entry_day_type'),
               type_=postgresql.ENUM('WORKING_DAY', 'HOLIDAY', 'SUNDAY', 'LEAVE', name='pms_day_type'),
               existing_nullable=False)
    op.drop_index('ix_pms_monthly_metrics_record_id', table_name='pms_monthly_metrics')
    op.drop_table('pms_monthly_metrics')
    op.drop_index('ix_pms_monthly_records_year_month', table_name='pms_monthly_records')
    op.drop_index('ix_pms_monthly_records_user_id', table_name='pms_monthly_records')
    op.drop_table('pms_monthly_records')
    op.drop_index('ix_pms_metric_configs_display_order', table_name='pms_metric_configs')
    op.drop_table('pms_metric_configs')
    op.drop_table('pms_employee_of_month_selections')
    # ### end Alembic commands ###
