"""add_offer_direction

Revision ID: 96327c3b9b6c
Revises: 20260702_0027
Create Date: 2026-07-04 11:42:15.921097

"""
from alembic import op
import sqlalchemy as sa



revision = '96327c3b9b6c'
down_revision = '20260702_0027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_sla_history_conversation_id_fkey'), 'conversation_sla_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_sla_history', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_sla_history', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_sla_history_conversation_id_fkey'), 'conversation_sla_history', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
