""" 

Revision ID: afc485467ba5
Revises: 20260619_0011
Create Date: 2026-06-19 17:12:13.863075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'afc485467ba5'
down_revision = '20260619_0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.alter_column('category_user_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_category_user_assignments_category_id'), table_name='category_user_assignments')
    op.drop_index(op.f('ix_category_user_assignments_user_id'), table_name='category_user_assignments')
    op.drop_constraint(op.f('uq_category_user_assignments_category_user'), 'category_user_assignments', type_='unique')
    op.drop_constraint(op.f('category_user_assignments_user_id_fkey'), 'category_user_assignments', type_='foreignkey')
    op.drop_constraint(op.f('category_user_assignments_category_id_fkey'), 'category_user_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'category_user_assignments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'category_user_assignments', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_conversation_notes_author_id'), table_name='conversation_notes')
    op.drop_index(op.f('ix_conversation_notes_conversation_id'), table_name='conversation_notes')
    op.drop_constraint(op.f('conversation_notes_conversation_id_fkey'), 'conversation_notes', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_notes', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_ebay_accounts_ebay_username_lower_unique'), table_name='ebay_accounts')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_notifications_resource'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_resource'), 'notifications', ['resource_type', 'resource_id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_ebay_accounts_ebay_username_lower_unique'), 'ebay_accounts', [sa.literal_column('lower(ebay_username::text)')], unique=True)
    op.drop_constraint(None, 'conversation_notes', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_notes_conversation_id_fkey'), 'conversation_notes', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_notes_conversation_id'), 'conversation_notes', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_notes_author_id'), 'conversation_notes', ['author_id'], unique=False)
    op.drop_constraint(None, 'category_user_assignments', type_='foreignkey')
    op.drop_constraint(None, 'category_user_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('category_user_assignments_category_id_fkey'), 'category_user_assignments', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('category_user_assignments_user_id_fkey'), 'category_user_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_category_user_assignments_category_user'), 'category_user_assignments', ['category_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_category_user_assignments_user_id'), 'category_user_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_category_user_assignments_category_id'), 'category_user_assignments', ['category_id'], unique=False)
    op.alter_column('category_user_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
