"""task management refactor: source types + pms remarks

Revision ID: ba1cf64ff078
Revises: 497fc21b0a15
Create Date: 2026-08-04 10:50:26.604779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'ba1cf64ff078'
down_revision = '497fc21b0a15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_best_offer_state_account_checked'), table_name='ebay_best_offer_listing_sync_states')
    op.drop_constraint(op.f('uq_offer_management_entries_listing_id'), 'offer_management_entries', type_='unique')
    op.alter_column('offers', 'listing_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=32),
               nullable=True)
    op.alter_column('offers', 'offer_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('offers', 'offer_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('offers', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_offers_account_listing_buyer'), table_name='offers')
    op.drop_index(op.f('ix_offers_conversation_provider_time'), table_name='offers')
    op.drop_index(op.f('ix_offers_lookup'), table_name='offers')
    op.drop_index(op.f('ix_offers_provider_offer_id'), table_name='offers')
    op.create_index(op.f('ix_offers_provider_offer_id'), 'offers', ['provider_offer_id'], unique=False)
    op.drop_constraint(op.f('fk_offers_message_id_messages'), 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'messages', ['message_id'], ['id'])
    op.add_column('pms_daily_task_entries', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pms_daily_task_entries', 'remarks')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_offers_message_id_messages'), 'offers', 'messages', ['message_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_offers_provider_offer_id'), table_name='offers')
    op.create_index(op.f('ix_offers_provider_offer_id'), 'offers', ['provider_offer_id'], unique=True)
    op.create_index(op.f('ix_offers_lookup'), 'offers', ['account_id', 'listing_id', 'buyer_username'], unique=False)
    op.create_index(op.f('ix_offers_conversation_provider_time'), 'offers', ['conversation_id', 'created_at_provider', 'created_at'], unique=False)
    op.create_index(op.f('ix_offers_account_listing_buyer'), 'offers', ['account_id', 'listing_id', 'buyer_username'], unique=False)
    op.alter_column('offers', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('offers', 'offer_type',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('offers', 'offer_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('offers', 'listing_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(op.f('uq_offer_management_entries_listing_id'), 'offer_management_entries', ['listing_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_best_offer_state_account_checked'), 'ebay_best_offer_listing_sync_states', ['account_id', 'last_checked_at'], unique=False)
    # ### end Alembic commands ###
