"""adding rply functionality

Revision ID: dccd15e43977
Revises: 20260619_0012
Create Date: 2026-06-19 17:41:57.839458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'dccd15e43977'
down_revision = '20260619_0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_provider_attachment_id'), table_name='message_attachments')
    op.drop_constraint(op.f('message_attachments_message_id_fkey'), 'message_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'message_attachments', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('message_attachments_message_id_fkey'), 'message_attachments', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_message_attachments_provider_attachment_id'), 'message_attachments', ['provider_attachment_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.alter_column('message_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
