"""add store_name to ebay_accounts

Revision ID: fba04a28d0a8
Revises: 20260617_0007
Create Date: 2026-06-17 10:22:55.786629

"""
from alembic import op
import sqlalchemy as sa



revision = 'fba04a28d0a8'
down_revision = '20260617_0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_name_lower'), table_name='categories')
    op.drop_index(op.f('ix_category_keywords_category_id'), table_name='category_keywords')
    op.drop_index(op.f('ix_category_keywords_category_id_keyword_lower'), table_name='category_keywords')
    op.drop_constraint(op.f('category_keywords_category_id_fkey'), 'category_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'category_keywords', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_conversation_assignments_assigned_to'), table_name='conversation_assignments')
    op.drop_index(op.f('ix_conversation_assignments_current'), table_name='conversation_assignments', postgresql_where='(unassigned_at IS NULL)')
    op.drop_constraint(op.f('conversation_assignments_conversation_id_fkey'), 'conversation_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_assignments', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_conversation_category_history_conversation_id'), table_name='conversation_category_history')
    op.drop_constraint(op.f('conversation_category_history_conversation_id_fkey'), 'conversation_category_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_category_history', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_participant_identifier'), table_name='conversation_participants')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_conversation_status_history_conversation_id'), table_name='conversation_status_history')
    op.drop_constraint(op.f('conversation_status_history_conversation_id_fkey'), 'conversation_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_status_history', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_conversations_category_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_provider'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_provider_account_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_ebay_accounts_ebay_username'), table_name='ebay_accounts')
    op.drop_index(op.f('ix_ebay_accounts_oauth_state'), table_name='ebay_accounts')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_sync_logs_provider'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_provider_account_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_logs_provider_account_id'), 'sync_logs', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_provider'), 'sync_logs', ['provider'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ebay_accounts_oauth_state'), 'ebay_accounts', ['oauth_state'], unique=False)
    op.create_index(op.f('ix_ebay_accounts_ebay_username'), 'ebay_accounts', ['ebay_username'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_provider_account_id'), 'conversations', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_conversations_provider'), 'conversations', ['provider'], unique=False)
    op.create_index(op.f('ix_conversations_category_id'), 'conversations', ['category_id'], unique=False)
    op.drop_constraint(None, 'conversation_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_status_history_conversation_id_fkey'), 'conversation_status_history', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_status_history_conversation_id'), 'conversation_status_history', ['conversation_id'], unique=False)
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_participants_participant_identifier'), 'conversation_participants', ['participant_identifier'], unique=False)
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.drop_constraint(None, 'conversation_category_history', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_category_history_conversation_id_fkey'), 'conversation_category_history', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_category_history_conversation_id'), 'conversation_category_history', ['conversation_id'], unique=False)
    op.drop_constraint(None, 'conversation_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_assignments_conversation_id_fkey'), 'conversation_assignments', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversation_assignments_current'), 'conversation_assignments', ['conversation_id'], unique=False, postgresql_where='(unassigned_at IS NULL)')
    op.create_index(op.f('ix_conversation_assignments_assigned_to'), 'conversation_assignments', ['assigned_to'], unique=False)
    op.drop_constraint(None, 'category_keywords', type_='foreignkey')
    op.create_foreign_key(op.f('category_keywords_category_id_fkey'), 'category_keywords', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_category_keywords_category_id_keyword_lower'), 'category_keywords', ['category_id', sa.literal_column('lower(keyword::text)')], unique=True)
    op.create_index(op.f('ix_category_keywords_category_id'), 'category_keywords', ['category_id'], unique=False)
    op.create_index(op.f('ix_categories_name_lower'), 'categories', [sa.literal_column('lower(name::text)')], unique=True)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    # ### end Alembic commands ###
