import { useEffect, useState } from 'react'
import AppLayout from '../layouts/app_layout'
import { createMessageType, deleteMessageType, fetchMessageTypes, setMessageTypeStatus, updateMessageType } from '../services/messageTypeApi'

function flatten(nodes, depth = 0) { return nodes.flatMap((node) => [{ ...node, depth }, ...flatten(node.children || [], depth + 1)]) }

export default function MessageTypes({ currentUser, onLogout }) {
  const [tree, setTree] = useState([]); const [form, setForm] = useState({ name: '', parent_id: '', description: '', display_order: 0 }); const [editing, setEditing] = useState(''); const [error, setError] = useState('')
  async function load() { try { setTree(await fetchMessageTypes(true)); setError('') } catch (e) { setError(e.message) } }
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [])
  async function submit(event) { event.preventDefault(); try { const payload = { ...form, parent_id: form.parent_id || null, display_order: Number(form.display_order) }; if (editing) await updateMessageType(editing, payload); else await createMessageType(payload); setForm({ name: '', parent_id: '', description: '', display_order: 0 }); setEditing(''); await load() } catch (e) { setError(e.message) } }
  const items = flatten(tree)
  return <AppLayout activePage="Message Types" currentUser={currentUser} onLogout={onLogout}><main className="management-page"><div className="page-header"><div><h1>Message Types</h1><p>Manage reply classifications and hierarchy.</p></div></div>{error ? <p className="form-message error">{error}</p> : null}<form className="analytics-filter-bar" onSubmit={submit}><label className="field"><span>Name</span><input required value={form.name} onChange={(e) => setForm({...form, name:e.target.value})}/></label><label className="field"><span>Parent</span><select value={form.parent_id} onChange={(e) => setForm({...form, parent_id:e.target.value})}><option value="">Root category</option>{items.filter((x) => x.id !== editing && !x.is_deleted).map((x) => <option value={x.id} key={x.id}>{'— '.repeat(x.depth)}{x.name}</option>)}</select></label><label className="field"><span>Order</span><input type="number" min="0" value={form.display_order} onChange={(e) => setForm({...form, display_order:e.target.value})}/></label><label className="field"><span>Description</span><input value={form.description} onChange={(e) => setForm({...form, description:e.target.value})}/></label><div className="analytics-filter-actions"><button className="primary-button compact" type="submit">{editing ? 'Save' : 'Create'}</button></div></form><section className="analytics-panel"><div className="report-table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td style={{paddingLeft:`${16 + item.depth * 24}px`}}>{item.name}</td><td>{item.is_deleted ? 'Deleted' : item.is_active ? 'Active' : 'Inactive'}</td><td>{item.display_order}</td><td><button className="secondary-button compact-action" onClick={() => { setEditing(item.id); setForm({name:item.name,parent_id:item.parent_id || '',description:item.description || '',display_order:item.display_order}) }}>Edit</button> {item.is_deleted ? <button className="secondary-button compact-action" onClick={async () => { await setMessageTypeStatus(item.id,{restore:true,is_active:true}); load() }}>Restore</button> : <><button className="secondary-button compact-action" onClick={async () => { await setMessageTypeStatus(item.id,{is_active:!item.is_active}); load() }}>{item.is_active ? 'Disable' : 'Enable'}</button> <button className="secondary-button compact-action" onClick={async () => { await deleteMessageType(item.id); load() }}>Delete</button></>}</td></tr>)}</tbody></table></div></section></main></AppLayout>
}
